_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "models/R-50Imagenet_backboneonly.pkl" #R50 backbone trained on ImageNet from https://dl.fbaipublicfiles.com/detectron2/ImageNetPretrained/MSRA/R-50.pkl
  ROI_HEADS:
    NUM_CLASSES: 80
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024) #, 928, 960, 992, 1024)
DATASETS:
  TRAIN: ("coco_sparse_easy",)
  TEST: ("coco_val",)
  BATCH_CONTENTS: ("labeled_strong","labeled_weak",)
  BATCH_RATIOS: (1,1,)
EMA:
  ENABLED: True
DOMAIN_ADAPT:
  TEACHER:
    ENABLED: True
    THRESHOLD: 0.6
  DISTILL:
    DISTILLER_NAME: SparseStudentTeacherDistiller
    HARD_ROIH_CLS_ENABLED: True
    HARD_ROIH_REG_ENABLED: True
    HARD_OBJ_ENABLED: True
    HARD_RPN_REG_ENABLED: True
SAOD:
  LABELING_METHOD: "CoStudent" # or "CoStudent", "StudentTeacher"
SOLVER:
  STEPS: (20000,30000,) # 
  MAX_ITER: 40000 # 3 X 3000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.001
OUTPUT_DIR: "outputs/coco/coco_costudent_sparse_easy/"
LOGGING:
  TAGS: "SAOD,RCCN-FPN"