_BASE_: "../MeanTeacher-urchininf.yaml"
MODEL:
  FIND_UNUSED_PARAMETERS: True
  META_ARCHITECTURE: "ExtraRCNN"
DATASETS:
  BATCH_CONTENTS: ("labeled_weak", "unlabeled_strong")
  BATCH_RATIOS: (1,1)
AUG:
  LABELED_INCLUDE_RANDOM_ERASING: False
  UNLABELED_INCLUDE_RANDOM_ERASING: False
  UNLABELED_MIC_AUG: True
DOMAIN_ADAPT:
  LOSSES:
    QUALITY_LOSS_WEIGHT_ENABLED: True
  ALIGN:
    SADA_ENABLED: True
SOLVER:
  STEPS: (8999,)
OUTPUT_DIR: "outputs/urchininf/urchininf_MIC/"
LOGGING:
  TAGS: "RCCN-FPN,MIC"