_BASE_: "../urchininf_baseline/Probabilistic-RCNN-FPN-urchininf.yaml"
MODEL:
  META_ARCHITECTURE: "ExtraRCNN"
  WEIGHTS: "outputs/urchininf/urchininf_ptbaseline/model_final.pth"
EMA:
  ENABLED: True
DATASETS:
  UNLABELED: ("UDD_train",)
  BATCH_CONTENTS: ("labeled_weak", "labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,1,1)
GRCNN:
  LEARN_ANCHORS_LABELED: False
  LEARN_ANCHORS_UNLABELED: True
  EFL: True
SOLVER:
  STEPS: (2599,)
  MAX_ITER: 2600
  #BASE_LR: 0.01
  IMS_PER_BATCH: 24  
  IMS_PER_GPU: 3
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 10.0 # this mimics PT trainer
DOMAIN_ADAPT:
  TEACHER:
    PSEUDO_LABEL_METHOD: "probabilistic"
OUTPUT_DIR: "outputs/urchininf/urchininf_pt/"
LOGGING:
  TAGS: "RCCN-FPN,PT,Inf2UDD"