_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 8
DATASETS:
  TRAIN: ("cityscapes_train",)
  TEST: ("cityscapes_foggy_val",)
  BATCH_CONTENTS: ("labeled_strong", )
UMS:
  UNLABELED: ("cityscapes_foggy_train",)
EMA:
  ENABLED: True
SOLVER:
  STEPS: (9999,)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 500
OUTPUT_DIR: "outputs/cityscapes/cityscapes_baseline_strongaug_ema/"
LOGGING:
  TAGS: "Base,RCCN-FPN,StrongAugEMA"