_BASE_: "../Base-DETR.yaml"
MODEL:
  DEFORMABLE_DETR:
    NUM_CLASSES: 8
DATASETS:
  TRAIN: ("cityscapes_train",)
  TEST: ("cityscapes_foggy_val",) #("cityscapes_val", "cityscapes_foggy_val",)
  BATCH_CONTENTS: ("labeled_strong", )
UMS:
  UNLABELED: "cityscapes_foggy_val"
EMA:
  ENABLED: True
  START_ITER: 1500
SOLVER:
  STEPS: (9999,)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 100
OUTPUT_DIR: "outputs/cityscapes/cityscapes_baseline_detr_strongaug_ema/"
