_BASE_: "./Base-RCNN-FPN-imosauv_strongaug_ema.yaml"
MODEL:
  WEIGHTS: "outputs/imosauv/imosauv_baseline_strongaug_ema/model_final.pth" 
EMA:
  ENABLED: True
DATASETS:
  UNLABELED: ("UDD_train",)
  BATCH_CONTENTS: ("labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,1)
DOMAIN_ADAPT:
  TEACHER:
    ENABLED: True
  DISTILL:
    HARD_ROIH_CLS_ENABLED: False
    HARD_ROIH_REG_ENABLED: False
    HARD_OBJ_ENABLED: False
    HARD_RPN_REG_ENABLED: False
    ROIH_CLS_ENABLED: True
    OBJ_ENABLED: True
    ROIH_REG_ENABLED: True
    RPN_REG_ENABLED: True
AUG:
  LABELED_INCLUDE_RANDOM_ERASING: True
  UNLABELED_INCLUDE_RANDOM_ERASING: False
  LABELED_MIC_AUG: False
  UNLABELED_MIC_AUG: True
SOLVER:
  STEPS: (29999,)
  MAX_ITER: 30000 # 3X 15,000 - dropped to 40,000
  CHECKPOINT_PERIOD: 3000
OUTPUT_DIR: "outputs/imosauv/imosauv_ALDI_last/"
LOGGING:
  TAGS: "RCCN-FPN,ALDI"