_BASE_: "./Base-RCNN-FPN-imosauv_strongaug_ema.yaml"
MODEL:
  WEIGHTS: "outputs/imosauv/imosauv_baseline_strongaug_ema_udd/model_final.pth"
EMA:
  ENABLED: True
DATASETS:
  UNLABELED: ("UDD_train",)
  BATCH_CONTENTS: ("labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,1)
SOLVER:
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.01
DOMAIN_ADAPT:
  TEACHER:
    ENABLED: True
  DISTILL:
    HARD_ROIH_CLS_ENABLED: False
    HARD_ROIH_REG_ENABLED: False
    HARD_OBJ_ENABLED: False
    HARD_RPN_REG_ENABLED: False
    ROIH_CLS_ENABLED: True
    OBJ_ENABLED: True
    ROIH_REG_ENABLED: True
    RPN_REG_ENABLED: True
AUG:
  LABELED_INCLUDE_RANDOM_ERASING: True
  UNLABELED_INCLUDE_RANDOM_ERASING: False
  LABELED_MIC_AUG: False
  UNLABELED_MIC_AUG: True
UMS:
  UNLABELED: None
OUTPUT_DIR: "outputs/imosauv/imosauv_ALDI_final/"
LOGGING:
  TAGS: "RCCN-FPN,ALDI_final"