_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("squidle_urchin_train",)
  TEST: ("UDD_test",) #("squidle_urchin_2011_test","UDD_test",)
  BATCH_CONTENTS: ("labeled_strong", )
UMS:
  UNLABELED: ("UDD_train",)
EMA:
  ENABLED: True
SOLVER:
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 500
LOGGING:
  TAGS: "Base,RCCN-FPN,StrongAugEMA"
OUTPUT_DIR: "outputs/imosauv/imosauv_baseline_strongaug_ema_udd/"
