_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  #WEIGHTS: "/home/heather/GitHub/aldi/outputs/redcup/redcup_baseline_strongaug_ema/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("loose_redcup_train",)
  TEST: ("squidle_redcup_test",)
  BATCH_CONTENTS: ("labeled_strong", )
EMA:
  ENABLED: True
SOLVER:
  STEPS: (17999,) # 
  MAX_ITER: 18000 # 3 X 3000
  CHECKPOINT_PERIOD: 1000
  IMS_PER_GPU: 4
LOGGING:
  TAGS: "Base,RCCN-FPN,StrongAugEMA"
OUTPUT_DIR: "outputs/redcup/redcup_baseline_strongaug_ema/"
LOGGING:
  TAGS: "Base,RCCN-FPN,StrongAugEMA"