_BASE_: "../Base-FCOS.yaml"
MODEL:
  FCOS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("loose_urchin17714_train_og_only",)
  TEST: ("squidle_urchin_2011_test",)
  BATCH_CONTENTS: ("labeled_strong","labeled_weak",)
  BATCH_RATIOS: (1,1,)
EMA:
  ENABLED: True
DOMAIN_ADAPT:
  TEACHER:
    ENABLED: True
    THRESHOLD: 0.6
  DISTILL:
    DISTILLER_NAME: SparseStudentTeacherDistiller
    HARD_ROIH_CLS_ENABLED: True
    HARD_ROIH_REG_ENABLED: True
    HARD_OBJ_ENABLED: True
    HARD_RPN_REG_ENABLED: True
SAOD:
  LABELING_METHOD: "WeakTeacherWStrongStudentW" # or "CoStudent", "StudentTeacher"
  WEAK_LOSS: 1.0
  STRONG_LOSS: 1.0
TEST:
  EVAL_PERIOD: 2000
SOLVER:
  #STEPS: (6000, 8000,) #
  #MAX_ITER: 9001 # 3 X 3000
  CHECKPOINT_PERIOD: 1000
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
LOGGING:
  TAGS: "SAOD,FCOS"
OUTPUT_DIR: "outputs/imosauv/urchin_fcos_saod/"

