_BASE_: "./ALDI-urchininf.yaml"
DATASETS:
  BATCH_CONTENTS: ("labeled_strong", "unlabeled_strong","labeled_multiimgaug","unlabeled_multiimgaug",)
  BATCH_RATIOS: (1,1,0,0)
AUG:
  MOSAIC: True
  MOSAIC_P: 0.25
OUTPUT_DIR: "outputs/urchininf/urchininf_ALDI_mosaic/"
LOGGING:
  TAGS: "RCCN-FPN,ALDI,Mosaic0.25"