_BASE_: "./ALDI-urchininf.yaml"
MODEL:
  WEIGHTS: "outputs/urchininf/urchininf_baseline_strongaug_ema_udd/UDD_train_umsdas_ioukl_model_best.pth"
UMS:
  UNLABELED: ("UDD_train",)
OUTPUT_DIR: "outputs/urchininf/urchininf_aldi_udd_ums/"
LOGGING:
  TAGS: "RCCN-FPN,ALDI_ums"