_BASE_: "./Base-RCNN-VitDetB-urchininf_strongaug_ema.yaml"
MODEL:
  WEIGHTS: "outputs/urchininf/base_vitdetb_strongaug_ema_inf_udd/model_final.pth" 
EMA:
  ENABLED: True
DATASETS:
  BATCH_CONTENTS: ("labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,1)
DOMAIN_ADAPT:
  TEACHER:
    ENABLED: True
  DISTILL:
    HARD_ROIH_CLS_ENABLED: False
    HARD_ROIH_REG_ENABLED: False
    HARD_OBJ_ENABLED: False
    HARD_RPN_REG_ENABLED: False
    ROIH_CLS_ENABLED: True
    OBJ_ENABLED: True
    ROIH_REG_ENABLED: True
    RPN_REG_ENABLED: True
AUG:
  LABELED_INCLUDE_RANDOM_ERASING: True
  UNLABELED_INCLUDE_RANDOM_ERASING: False
  LABELED_MIC_AUG: False
  UNLABELED_MIC_AUG: True
OUTPUT_DIR: "outputs/urchininf/urchininf_ALDI_vitb/"
LOGGING:
  TAGS: "RCCN-VitDetB,ALDI"