_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("urchininf_v0_train",)
  TEST: ("UDD_test",)
  BATCH_CONTENTS: ("labeled_strong", )
EMA:
  ENABLED: True
OUTPUT_DIR: "outputs/urchininf/urchininf_baseline_strongaug_ema/"
LOGGING:
  TAGS: "Base,RCCN-FPN,StrongAugEMA"