_BASE_: "Base-urchininf-data.yaml"
DATASETS:
  BATCH_CONTENTS: ("labeled_weak", )
EMA:
  ENABLED: False
OUTPUT_DIR: "outputs/urchininf/urchininf_base_weakaug/"
LOGGING:
  TAGS: "Base,RCCN-FPN,WeakAug"