_BASE_: "Base-RCNN-FPN-urchininf_strongaug_ema.yaml"
AUG:
  MOSAIC: True
  MOSAIC_P: 0.25
DATASETS:
  BATCH_CONTENTS: ("labeled_strong", "labeled_multiimgaug",)
  BATCH_RATIOS: (1,0)
EMA:
  ENABLED: True
OUTPUT_DIR: "outputs/urchininf/urchininf_base_strongaugmosaic025_ema/"
LOGGING:
  TAGS: "Base,RCCN-FPN,StrongAugEMA,Mosaic0.25"