_BASE_: "Base-RCNN-FPN-urchininf_strongaug_ema.yaml"
AUG:
  LABELED_INCLUDE_RANDOM_ERASING: True
  UNLABELED_INCLUDE_RANDOM_ERASING: False
  LABELED_MIC_AUG: False
  UNLABELED_MIC_AUG: True
LOGGING:
  TAGS: "Base,RCCN-FPN,StrongCutAugEMA"