_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("urchininf_v0_train","urchininf_rov_v1_train","urchininf_auv_v2_train",)
  TEST: ("UDD_test",)
  UNLABELED: ("squidle_urchin_2009_train","squidle_east_tas_urchins_train",)
SOLVER:
  IMS_PER_BATCH: 16
  IMS_PER_GPU: 8