_BASE_: "Base-RCNN-FPN-urchininf_strongaug_ema.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("urchininf_v0_train","urchininf_rov_v1_train")
  TEST: ("UDD_test",)
  BATCH_CONTENTS: ("labeled_strong", "labeled_multiimgaug",)
  BATCH_RATIOS: (1,1)
EMA:
  ENABLED: False
SOLVER:
  IMS_PER_BATCH: 8
  IMS_PER_GPU: 4
OUTPUT_DIR: "outputs/urchininf/urchininf_base_strongaugmosaic_ema/"
LOGGING:
  TAGS: "Base,RCCN-FPN,StrongAug,Mosaic"