_BASE_: "Base-RCNN-FPN-urchininf_strongaug_ema.yaml"
DATASETS:
  TEST: ("squidle_urchin_2011_test",)
  UNLABELED: ("squidle_urchin_2009_train","squidle_east_tas_urchins_train",)
  BATCH_CONTENTS: ("labeled_weak", )
UMS:
  UNLABELED: ("squidle_urchin_train",)
OUTPUT_DIR: "outputs/urchininf/urchininf_baseline_strongaug_ema_sq/"
