_BASE_: "Base-RCNN-VitDetB-urchininf_strongaug_ema.yaml"
DATASETS:
  TEST: ("squidle_urchin_2011_test",)
  UNLABELED: ("squidle_urchin_2009_train","squidle_east_tas_urchins_train",)
  BATCH_CONTENTS: ("labeled_weak", )
