_BASE_: "./MeanTeacher-VitDetB-urchininf.yaml"
MODEL:
  WEIGHTS: "outputs/urchininf/base_vitdetb_strongaug_ema_inf_sq/model_final.pth"  #urchininf_base_strongaug_ema
DATASETS:
  UNLABELED: ("squidle_urchin_2009_train","squidle_east_tas_urchins_train",)
  TEST: ("squidle_urchin_2011_test",)
