_BASE_: "./Base-RCNN-FPN-urchininf_strongaug_ema.yaml"
MODEL:
  WEIGHTS: "outputs/urchininf/urchininf_baseline_strongaug_ema_udd/UDD_urchin_train_umsdas_ioukl_model_best.pth"
EMA:
  ENABLED: True
DATASETS:
  BATCH_CONTENTS: ("labeled_weak", "labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,1,1)
DOMAIN_ADAPT:
  TEACHER:
    ENABLED: True
  DISTILL:
    # By default, disable localization losses (done by AT, UBT, MIC, ...)
    HARD_ROIH_CLS_ENABLED: True
    HARD_ROIH_REG_ENABLED: False
    HARD_OBJ_ENABLED: True
    HARD_RPN_REG_ENABLED: False
SOLVER:
  IMS_PER_BATCH: 24 # was 24 with BASE_LR 0.03
  BASE_LR: 0.03 
UMS:
  UNLABELED: ("UDD_train",)
OUTPUT_DIR: "outputs/urchininf/urchininf_meanteacher_udd_ums/"
LOGGING:
  TAGS: "RCCN-FPN,MT_ums"