_BASE_: "./MeanTeacher-urchininf.yaml"
DATASETS:
  UNLABELED: ("squidle_urchin_2009_train","squidle_east_tas_urchins_train",)
  TEST: ("squidle_urchin_2011_test",)
MODEL:
  WEIGHTS: "outputs/urchininf/base_strongaug_ema_inf_sq/model_final.pth"  #urchininf_base_strongaug_ema