_BASE_: "../Base-RCNN-VitDetB.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("UDD_train",)
  TEST: ("UDD_test",)
  BATCH_CONTENTS: ("labeled_strong", )
EMA:
  ENABLED: True
OUTPUT_DIR: "outputs/urchininf/urchininf_oracle_vitdetb_strongaug_ema_udd/"
LOGGING:
  TAGS: "RCCN-VitDetB,Oracle,StrongAugEMA"