_BASE_: "./Base-urchininf-data.yaml"
MODEL:
  #WEIGHTS: "outputs/urchininf/urchininf_baseline_strongaug_ema/model_0007999.pth"
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("urchininf_v0_train","urchininf_rov_v1_train","urchininf_auv_v2_train",)
  TEST: ("UDD_test",)
  BATCH_CONTENTS: ("labeled_strong", )
EMA:
  ENABLED: True
SOLVER:
  STEPS: (8999,) # 
  MAX_ITER: 9000 # 3 X 3000
  CHECKPOINT_PERIOD: 100
  IMS_PER_BATCH: 4 # Batch = 16 with 2 per GPU with 8 GPU = 0.02 LR
  IMS_PER_GPU: 4
TEST:
  EVAL_PERIOD: 500
UMS:
  UNLABELED: "UDD_test"
LOGGING:
  TAGS: "Base,RCCN-FPN,StrongAugEMA"
OUTPUT_DIR: "outputs/urchininf/urchininf_baseline_strongaug_ema_ums/"
LOGGING:
  TAGS: "Base,RCCN-FPN,StrongAugEMA"



