_BASE_: "./Base-RCNN-FPN_og.yaml"
MODEL:
  WEIGHTS: "models/model_final_f10217.pkl" # "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x" from detectron2
  FIND_UNUSED_PARAMETERS: False
SOLVER:
  BASE_LR: 0.02 # LR should be appropriate for IMS_PER_BATCH and MAX_ITERS
  STEPS: (6000, 8000) 
  MAX_ITER: 9001 # Reduced by factor of 10 9000
  IMS_PER_BATCH: 16 # Batch = 16 with 2 per GPU with 8 GPU = 0.02 LR
  IMS_PER_GPU: 8
  CHECKPOINT_PERIOD: 2000 #2000
VIS_PERIOD: 0 
TEST:
  EVAL_PERIOD: 500
LOGGING:
  API_TOKEN: "=="
  PROJECT: "ACFRmarine/ALDI-DOAD" 
  ITERS: 100
  PROXY: ""
SEED: 1234567
