#!/bin/bash

#CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py  --dist-url 'tcp://127.0.0.1:50162' --num-gpus 2 --config-file configs/urchininf/Base-RCNN-FPN-urchininf_strongaug_ema.yaml OUTPUT_DIR \'outputs/urchininf/base_strongaug_ema_inf_udd25/\' LOGGING.GROUP_TAGS Inf+25tgt2UDD,T5  DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'UDD_train_split_25\',\)
CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py  --dist-url 'tcp://127.0.0.1:50162' --resume how to --num-gpus 2 --config-file configs/urchininf/Base-RCNN-FPN-urchininf_strongaug_ema.yaml OUTPUT_DIR \'outputs/urchininf/base_strongaug_ema_inf_udd50/\' LOGGING.GROUP_TAGS Inf+50tgt2UDD,T5  DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'UDD_train_split_50\',\)
CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py  --dist-url 'tcp://127.0.0.1:50162' --num-gpus 2 --config-file configs/urchininf/Base-RCNN-FPN-urchininf_strongaug_ema.yaml OUTPUT_DIR \'outputs/urchininf/base_strongaug_ema_inf_udd100/\' LOGGING.GROUP_TAGS Inf+100tgt2UDD,T5  DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'UDD_train_split_100\',\)
CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py  --dist-url 'tcp://127.0.0.1:50162' --num-gpus 2 --config-file configs/urchininf/Base-RCNN-FPN-urchininf_strongaug_ema.yaml OUTPUT_DIR \'outputs/urchininf/base_strongaug_ema_inf_udd200/\' LOGGING.GROUP_TAGS Inf+200tgt2UDD,T5  DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'UDD_train_split_200\',\)
CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py  --dist-url 'tcp://127.0.0.1:50162' --num-gpus 2 --config-file configs/urchininf/Base-RCNN-FPN-urchininf_strongaug_ema.yaml OUTPUT_DIR \'outputs/urchininf/base_strongaug_ema_inf_udd400/\' LOGGING.GROUP_TAGS Inf+400tgt2UDD,T5  DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'UDD_train_split_400\',\)
CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py  --dist-url 'tcp://127.0.0.1:50162' --num-gpus 2 --config-file configs/urchininf/Base-RCNN-FPN-urchininf_strongaug_ema.yaml OUTPUT_DIR \'outputs/urchininf/base_strongaug_ema_inf_udd600/\' LOGGING.GROUP_TAGS Inf+600tgt2UDD,T5  DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'UDD_train_split_600\',\)
CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py  --dist-url 'tcp://127.0.0.1:50162' --num-gpus 2 --config-file configs/urchininf/Base-RCNN-FPN-urchininf_strongaug_ema.yaml OUTPUT_DIR \'outputs/urchininf/base_strongaug_ema_inf_udd1000/\' LOGGING.GROUP_TAGS Inf+1000tgt2UDD,T5  DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'UDD_train_split_1000\',\)
CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py  --dist-url 'tcp://127.0.0.1:50162' --num-gpus 2 --config-file configs/urchininf/Base-RCNN-FPN-urchininf_strongaug_ema.yaml OUTPUT_DIR \'outputs/urchininf/base_strongaug_ema_inf_udd1400/\' LOGGING.GROUP_TAGS Inf+1400tgt2UDD,T5  DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'UDD_train_split_1400\',\)
