#!/bin/bash

#CUDA_VISIBLE_DEVICES=0,1 python tools/train_net.py --num-gpus 2 --config-file configs/urchininf/OracleT-RCNN-FPN-urchininf_strongaug_ema.yaml OUTPUT_DIR \'outputs/urchininf/oracle_strongaug_ema_sq25/\' LOGGING.GROUP_TAGS 25Sq,T5 DATASETS.TEST \(\'squidle_urchin_2011_test\',\) DATASETS.TRAIN \(\'squidle_urchin_2009_train_split_25\',\)
#CUDA_VISIBLE_DEVICES=0,1 python tools/train_net.py --num-gpus 2 --config-file configs/urchininf/OracleT-RCNN-FPN-urchininf_strongaug_ema.yaml OUTPUT_DIR \'outputs/urchininf/oracle_strongaug_ema_sq50/\' LOGGING.GROUP_TAGS 50Sq,T5 DATASETS.TEST \(\'squidle_urchin_2011_test\',\) DATASETS.TRAIN \(\'squidle_urchin_2009_train_split_50\',\)
CUDA_VISIBLE_DEVICES=0,1 python tools/train_net.py --num-gpus 2 --config-file configs/urchininf/OracleT-RCNN-FPN-urchininf_strongaug_ema.yaml OUTPUT_DIR \'outputs/urchininf/oracle_strongaug_ema_sq100/\' LOGGING.GROUP_TAGS 100Sq,T5 DATASETS.TEST \(\'squidle_urchin_2011_test\',\) DATASETS.TRAIN \(\'squidle_urchin_2009_train_split_100\',\)
CUDA_VISIBLE_DEVICES=0,1 python tools/train_net.py --num-gpus 2 --config-file configs/urchininf/OracleT-RCNN-FPN-urchininf_strongaug_ema.yaml OUTPUT_DIR \'outputs/urchininf/oracle_strongaug_ema_sq200/\' LOGGING.GROUP_TAGS 200Sq,T5 DATASETS.TEST \(\'squidle_urchin_2011_test\',\) DATASETS.TRAIN \(\'squidle_urchin_2009_train_split_200\',\)
CUDA_VISIBLE_DEVICES=0,1 python tools/train_net.py --num-gpus 2 --config-file configs/urchininf/OracleT-RCNN-FPN-urchininf_strongaug_ema.yaml OUTPUT_DIR \'outputs/urchininf/oracle_strongaug_ema_sq400/\' LOGGING.GROUP_TAGS 400Sq,T5 DATASETS.TEST \(\'squidle_urchin_2011_test\',\) DATASETS.TRAIN \(\'squidle_urchin_2009_train_split_378\',\'squidle_east_tas_urchins_train_split_22\',\)
CUDA_VISIBLE_DEVICES=0,1 python tools/train_net.py --num-gpus 2 --config-file configs/urchininf/OracleT-RCNN-FPN-urchininf_strongaug_ema.yaml OUTPUT_DIR \'outputs/urchininf/oracle_strongaug_ema_sq600/\' LOGGING.GROUP_TAGS 600Sq,T5 DATASETS.TEST \(\'squidle_urchin_2011_test\',\) DATASETS.TRAIN \(\'squidle_urchin_2009_train_split_378\',\'squidle_east_tas_urchins_train_split_222\',\)
CUDA_VISIBLE_DEVICES=0,1 python tools/train_net.py --num-gpus 2 --config-file configs/urchininf/OracleT-RCNN-FPN-urchininf_strongaug_ema.yaml OUTPUT_DIR \'outputs/urchininf/oracle_strongaug_ema_sq1000/\' LOGGING.GROUP_TAGS 1000Sq,T5 DATASETS.TEST \(\'squidle_urchin_2011_test\',\) DATASETS.TRAIN \(\'squidle_urchin_2009_train_split_378\',\'squidle_east_tas_urchins_train_split_622\',\)
CUDA_VISIBLE_DEVICES=0,1 python tools/train_net.py --num-gpus 2 --config-file configs/urchininf/OracleT-RCNN-FPN-urchininf_strongaug_ema.yaml OUTPUT_DIR \'outputs/urchininf/oracle_strongaug_ema_sq1400/\' LOGGING.GROUP_TAGS 1400Sq,T5 DATASETS.TEST \(\'squidle_urchin_2011_test\',\) DATASETS.TRAIN \(\'squidle_urchin_2009_train_split_378\',\'squidle_east_tas_urchins_train_split_1022\',\)
