#!/bin/bash

#CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py  --dist-url 'tcp://127.0.0.1:50162' --num-gpus 2 --config-file configs/urchininf/Base-RCNN-FPN-urchininf_strongaug_ema_sq.yaml OUTPUT_DIR \'outputs/urchininf/base_strongaug_ema_inf_sq25/\' LOGGING.GROUP_TAGS Inf+25tgt2SQ,T5  DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'squidle_urchin_2009_train_split_25\',\)
CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py  --dist-url 'tcp://127.0.0.1:50162' --num-gpus 2 --resume --config-file configs/urchininf/Base-RCNN-FPN-urchininf_strongaug_ema_sq.yaml OUTPUT_DIR \'outputs/urchininf/base_strongaug_ema_inf_sq50/\' LOGGING.GROUP_TAGS Inf+50tgt2SQ,T5  DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'squidle_urchin_2009_train_split_50\',\) 
CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py  --dist-url 'tcp://127.0.0.1:50162' --num-gpus 2 --config-file configs/urchininf/Base-RCNN-FPN-urchininf_strongaug_ema_sq.yaml OUTPUT_DIR \'outputs/urchininf/base_strongaug_ema_inf_sq100/\' LOGGING.GROUP_TAGS Inf+100tgt2SQ,T5  DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'squidle_urchin_2009_train_split_100\',\)
CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py  --dist-url 'tcp://127.0.0.1:50162' --num-gpus 2 --config-file configs/urchininf/Base-RCNN-FPN-urchininf_strongaug_ema_sq.yaml OUTPUT_DIR \'outputs/urchininf/base_strongaug_ema_inf_sq200/\' LOGGING.GROUP_TAGS Inf+200tgt2SQ,T5  DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'squidle_urchin_2009_train_split_200\',\)
CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py  --dist-url 'tcp://127.0.0.1:50162' --num-gpus 2 --config-file configs/urchininf/Base-RCNN-FPN-urchininf_strongaug_ema_sq.yaml OUTPUT_DIR \'outputs/urchininf/base_strongaug_ema_inf_sq400/\' LOGGING.GROUP_TAGS Inf+400tgt2SQ,T5  DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'squidle_urchin_2009_train_split_378\',\'squidle_east_tas_urchins_train_split_22\',\)
CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py  --dist-url 'tcp://127.0.0.1:50162' --num-gpus 2 --config-file configs/urchininf/Base-RCNN-FPN-urchininf_strongaug_ema_sq.yaml OUTPUT_DIR \'outputs/urchininf/base_strongaug_ema_inf_sq600/\' LOGGING.GROUP_TAGS Inf+600tgt2SQ,T5  DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'squidle_urchin_2009_train_split_378\',\'squidle_east_tas_urchins_train_split_222\',\)
CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py  --dist-url 'tcp://127.0.0.1:50162' --num-gpus 2 --config-file configs/urchininf/Base-RCNN-FPN-urchininf_strongaug_ema_sq.yaml OUTPUT_DIR \'outputs/urchininf/base_strongaug_ema_inf_sq1000/\' LOGGING.GROUP_TAGS Inf+1000tgt2SQ,T5  DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'squidle_urchin_2009_train_split_378\',\'squidle_east_tas_urchins_train_split_622\',\)
CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py  --dist-url 'tcp://127.0.0.1:50162' --num-gpus 2 --config-file configs/urchininf/Base-RCNN-FPN-urchininf_strongaug_ema_sq.yaml OUTPUT_DIR \'outputs/urchininf/base_strongaug_ema_inf_sq1400/\' LOGGING.GROUP_TAGS Inf+1400tgt2SQ,T5  DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'squidle_urchin_2009_train_split_378\',\'squidle_east_tas_urchins_train_split_1022\',\)
