_BASE_: "./Base-RCNN-FPN-Sim10k_strongaug_ema.yaml"
MODEL:
  WEIGHTS: "outputs/sim10k/sim10k_baseline_strongaug_ema/cityscapes_cars_train_umsdas_ioukl_model_best.pth"
EMA:
  ENABLED: True
DATASETS:
  UNLABELED: ("cityscapes_cars_train",)
  BATCH_CONTENTS: ("labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,1)
DOMAIN_ADAPT:
  TEACHER:
    ENABLED: True
  DISTILL:
    HARD_ROIH_CLS_ENABLED: False
    HARD_ROIH_REG_ENABLED: False
    HARD_OBJ_ENABLED: False
    HARD_RPN_REG_ENABLED: False
    ROIH_CLS_ENABLED: True
    OBJ_ENABLED: True
    ROIH_REG_ENABLED: True
    RPN_REG_ENABLED: True
AUG:
  LABELED_INCLUDE_RANDOM_ERASING: True
  UNLABELED_INCLUDE_RANDOM_ERASING: False
  LABELED_MIC_AUG: False
  UNLABELED_MIC_AUG: True
OUTPUT_DIR: "outputs/sim10k/sim10k_ALDI_bestpre/"
LOGGING:
  TAGS: "RCCN-FPN,ALDI_bestpre"