_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("sim10k_cars_train",)
  TEST: ("cityscapes_cars_val",)
  BATCH_CONTENTS: ("labeled_weak", )
SOLVER:
  BASE_LR: 0.02 # LR should be appropriate for IMS_PER_BATCH and MAX_ITERS
  STEPS: (8999,) 
  MAX_ITER: 9000 # Reduced by factor of 10 9000 # Sim10k ALDI 3000
  IMS_PER_BATCH: 16 # Batch = 16 with 2 per GPU with 8 GPU = 0.02 LR
  IMS_PER_GPU: 8
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 100
OUTPUT_DIR: "outputs/sim10k/sim10k_baseline/"
LOGGING:
  TAGS: "Base,RCCN-FPN,WeakAug"