_BASE_: "./Base-RCNN-FPN-Sim10k_strongaug_ema.yaml"
MODEL:
  WEIGHTS: "outputs/sim10k/sim10k_baseline_strongaug_ema/cityscapes_cars_val_model_best.pth"
EMA:
  ENABLED: True
DATASETS:
  UNLABELED: ("cityscapes_cars_train",)
  BATCH_CONTENTS: ("labeled_weak", "labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,1,1)
DOMAIN_ADAPT:
  TEACHER:
    ENABLED: True
  DISTILL:
    # By default, disable localization losses (done by AT, UBT, MIC, ...)
    HARD_ROIH_CLS_ENABLED: True
    HARD_ROIH_REG_ENABLED: False
    HARD_OBJ_ENABLED: True
    HARD_RPN_REG_ENABLED: False
SOLVER:
  STEPS: (14999,)
  MAX_ITER: 15000
  CHECKPOINT_PERIOD: 2000
  BACKWARD_AT_END: False
  BASE_LR: 0.03 # LR should be appropriate for IMS_PER_BATCH and MAX_ITERS
  IMS_PER_BATCH: 24 # Batch = 16 with 2 per GPU with 8 GPU = 0.02 LR
UMS:
  UNLABELED: None
OUTPUT_DIR: "outputs/sim10k/sim10k_MT_max/"
LOGGING:
  TAGS: "RCCN-FPN,MT_max"