# SADA Inf With some Squidle target labeled data - Inf+no sq, 200, 400, 600, All sq+Inf
CUDA_VISIBLE_DEVICES=0,1 python tools/train_net.py --num-gpus 2 --config-file configs/urchininf/urchininf_priorart/SADA_urchininf.yaml OUTPUT_DIR \'outputs/urchininf/at_inf_sq/\' LOGGING.GROUP_TAGS Inf2UDD,T3 && \
CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py --num-gpus 2 --config-file configs/urchininf/urchininf_priorart/SADA_urchininf_sq.yaml OUTPUT_DIR \'outputs/urchininf/sada_inf_udd/\' LOGGING.GROUP_TAGS Inf2SQ,T3 && \
sudo shutdown
python tools/train_net.py --config-file configs/urchininf/urchininf_priorart/SADA_urchininf.yaml "OUTPUT_DIR \'outputs/urchininf/at_inf_udd100/\' LOGGING.GROUP_TAGS Inf+100tgt2UDD,T3 DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'UDD_train_split100\',\) "
python tools/train_net.py --config-file configs/urchininf/urchininf_priorart/SADA_urchininf_sq.yaml "OUTPUT_DIR \'outputs/urchininf/at_inf_sq100/\' LOGGING.GROUP_TAGS Inf+100tgt2SQ,T3 DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'squidle_urchin_2009_train_split100\',\) "
python tools/train_net.py --config-file configs/urchininf/urchininf_priorart/SADA_urchininf_sq.yaml "OUTPUT_DIR \'outputs/urchininf/at_inf_sqall/\' LOGGING.GROUP_TAGS Inf+alltgt2SQ,T3 DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'squidle_urchin_2009_train\',\'squidle_east_tas_urchins_train\',\) "
python tools/train_net.py --config-file configs/urchininf/urchininf_priorart/SADA_urchininf.yaml "OUTPUT_DIR \'outputs/urchininf/at_inf_uddall/\' LOGGING.GROUP_TAGS Inf+alltgt2UDD,T3 DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'UDD_train\',\) "
python tools/train_net.py --config-file configs/urchininf/urchininf_priorart/SADA_urchininf_sq.yaml "OUTPUT_DIR \'outputs/urchininf/at_inf_sq200/\' LOGGING.GROUP_TAGS Inf+200tgt2SQ,T3 DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'squidle_urchin_2009_train_split0\',\) "
python tools/train_net.py --config-file configs/urchininf/urchininf_priorart/SADA_urchininf_sq.yaml "OUTPUT_DIR \'outputs/urchininf/at_inf_sq400/\' LOGGING.GROUP_TAGS Inf+400tgt2SQ,T3 DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'squidle_urchin_2009_train_split0\',\'squidle_urchin_2009_train_split1\',\) "
python tools/train_net.py --config-file configs/urchininf/urchininf_priorart/SADA_urchininf.yaml "OUTPUT_DIR \'outputs/urchininf/at_inf_udd200/\' LOGGING.GROUP_TAGS Inf+200tgt2UDD,T3 DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'UDD_train_split0\',\) "
python tools/train_net.py --config-file configs/urchininf/urchininf_priorart/SADA_urchininf.yaml "OUTPUT_DIR \'outputs/urchininf/at_inf_udd400/\' LOGGING.GROUP_TAGS Inf+400tgt2UDD,T3 DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'UDD_train_split0\',\'UDD_train_split1\',\) "
python tools/train_net.py --config-file configs/urchininf/urchininf_priorart/SADA_urchininf.yaml "OUTPUT_DIR \'outputs/urchininf/at_inf_udd600/\' LOGGING.GROUP_TAGS Inf+600tgt2UDD,T3 DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'UDD_train_split0\',\'UDD_train_split1\',\'UDD_train_split2\',\) "
python tools/train_net.py --config-file configs/urchininf/urchininf_priorart/SADA_urchininf_sq.yaml "OUTPUT_DIR \'outputs/urchininf/at_inf_sq600/\' LOGGING.GROUP_TAGS Inf+600tgt2SQ,T3 DATASETS.TRAIN \(\'urchininf_v0_train\',\'urchininf_rov_v1_train\',\'urchininf_auv_v2_train\',\'squidle_urchin_2009_train_split0\',\'squidle_urchin_2009_train_split1\',\'squidle_urchin_2009_train_split2\',\) "
sudo shutdown