_BASE_: "../../Probabilistic-RCNN-FPN.yaml"
SOLVER:
  #BASE_LR: 0.01 # diverges with 0.06
  STEPS: (400,)
  MAX_ITER: 400
OUTPUT_DIR: "outputs/urchininf/urchininf_ptbaseline/"
LOGGING:
  TAGS: "RCCN-FPN,PTBase"